package ufrj.coppe.entities;

import java.util.HashMap;
import java.util.Map;

import ptstemmer.PTStemmerEX;
import ptstemmer.Stemmer;
import ptstemmer.Stemmer.StemmerType;

public class KeyWords {
	
	//public String type;
	
	public static int originais = 1;
	public static int originaisSteme = 2;
	public static int originaisOU = 3;
	public static int originaisOUSteme = 4;
	public static int reduzidasOriginais = 5;
	public static int reduzidasSteme = 6;
	public static int candidatasOriginais = 7;
	public static int candidatasSteme = 8;
	
	private static Map<Integer,String> keyWordsOriginais;
	private static Map<Integer,String> keyWordsReduzidas;
	private static Map<Integer,String> keyWordsCandidatasOriginais;
	private static Map<Integer,String> keyWordsCandidatasSteme;
	private static StemmerType orengoStemmer = Stemmer.StemmerType.ORENGO;
	
	static {
		keyWordsOriginais = new HashMap<Integer, String>();
		
		keyWordsOriginais.put(1,"moda,beleza,unissex,tendencia,infantil,infantojuvenil,roupas,criancas,bebe,cabelos,penteados,cores,cabelo,maquiagem,creme,rosto,batons,perfumes,esmaltes,unhas,base,blush,rimel,lapis,olho,tratamentos,esteticos,celulite,lipoaspiracao,cirurgia,plastica,silicone,estrias,relogio,masculino,feminino,mechas,hair,primaveraverao,visual,lantejoulas,vestido,longo,cinto,colete,");
		keyWordsOriginais.put(2,"veiculo,meio,transporte,locomocao,aviao,aviacao,helicoptero,aeronave,caminhao,caminhoes,caminhoneiro,piloto,onibus,trem,metro,audi,bmw,cadillac,chevrolet,citron,dodge,ferrari,fiat,ford,honda,hyundai,jaguar,kia,lamborghini,mazda,mercedes,benz,mitsubishi,nissan,peugeot,renault,toyota,volkswagen,automovel,amplificadores,audio,gol,uno,fox,celta,picanto,corsa,palio,stilo,punto,polo,astra,golf,focu,crossfox,poersch,linea,jetta,vectra,corolla,sentra,fluence,sedan,cerato,palla,montana,maserati,mercedez,rebaixamento,arrancadao,televan,van,venda_veiculos,venda_de_veiculos,translado,motorista,veiculos,");
		keyWordsOriginais.put(3,"Esporte,Esportivo,Competicao,esportiva,Desportivo,Desporte,Torneio,esportivo,Medalha,Podium,desportiva,Trofeu,Taca,Ginasta,Jogador,brasileirao,copa,sulamericana,mundial,clube,selecao,brasileira,taca,libertadores,gol,escanteio,penalti,tiro,meta,lateral,avante,atacante,meio,campo,zagueiro,goleiro,futebol,estadio,gandula,bola,chuteira,cigano,tuf,lutadore,cinturao,luta_livre,marciais,marcial,capoeira,judo,karate,judoca,carateca,boxe,mixed,martial,octogono,faixa_preta,rezende,rede,point,libero,levantador,basquete,basquetebol,nbb,nba,lakers,chicago,bulls,cesta,celtics,dallas,mavericks,miami,heat,harlem,globetrotters,knicks,esporte,radicai,aventura,expedicoes,paraquedismo,escalada,snowboard,montanhoso,rapel,rafting,base,jump,sky,surfing,delta,bungee,jumping,alpinismo,ginasio,paredao,arborismo,formula,stock,autodromos,interlagos,motocross,rally,desportos,motorizados,truck,atletismo,corrida,maratona,silvestre,salto,vara,distancia,lancamento,disco,peso,dardo,altura,prova_esportiva,metros,barreira,barreiras,ironman,campeonato,ciclismo,montain,bike,bmx,racing,freestyle,cbc,confederacao,mountain,mundo,olimpiada,jogo_panamericano,squash,tour,aruba,international,proam,golf,tournament,golfe,roller,patins,pista,skate,skatista,manobra,flip,grind,slide,ollie,olieflip,fakie,hardflip,kick,frontside,drop,steert,style,half,vertical,ramp,downhill,burnquist,remo,remadores,nauticos,canoagem,caiaque,mergulho,mergulhador,mergulhadores,submarina,esqui,aquatico,motonautica,natacao,polo,ornamentai,ornamental,nado,borboleta,peito,crawl,surf,surfe,surfista,rasgada,batida,floater,aereo,back,tubo,mick,fanning,bede,durbidge,hipismo,amazona,cavaleiro,equitacao,athina,onassis,horse,equestre,mundiai,dressage,concurso,completo,rodrigo,halterofilismo,wheyprotein,wheygold,golfistas,circuito,");
		keyWordsOriginais.put(4,"Casa,Construcao,Reforma,arquitetura,interiores,design,projetos,edificacoes,classica,construcao,ambientes,planejados,arquiteto,urbanismo,material,materiais,construtor,fundacao,acabamentos,planta,casa,terreno,telhado,contratacao,pedreiros,pedreiro,compra,materias,entulho,obra,azulejos,tintas,parede,caixa,agua,engenheiro,encanador,eletricista,mestre,obras,pisos,assento,banheiro,box,banheira,pia,granito,marmore,porcelanato,gesso,escada,vidro,cimento,tijolo,tinta,verniz,porta,janela,martelo,espatula,areia,argamassa,massa,corrida,mangueira,cal,betoneira,carrinho,prego,parafuso,parafusadeira,furadeiira,alicate,marreta,chave,fenda,trena,forro,pvc,madeira,vigas,decoracao,espacos,pequenos,decorados,dicas,almofadas,tapetes,objetos,utensilio,domesticos,cama,mesa,banho,fechadura,papel,luminaria,moveis,medidas,sofa,estante,centro,rack,cadeira,poltrona,closet,armario,guardaroupa,comoda,criadomudo,escrivaninha,penteadeira,beliche,bicama,banquetas,jardim,paisagismo,piscina,churrasqueira,area,lazer,salao,jogos,festas,varandas,paisagista,ideias,plantas,flores,orquideas,sementes,mudas,horta,");
		keyWordsOriginais.put(7,"imobiliaria,corretor,imoveis,preco,inflacao,aluguel,ajuste,locacao,venda,mrv,minha,casa,cohab,imobiliario,mercado,fundo,terreno,alugar,vender,sobrado,prefabricada,mobiliada,mobiliado,apartamento,prefabricado,planta,loft,kitinete,escritorios,galpoes,barracao,escritorio,comprar,sala,comercial,assessoria,imovel,sobradinho,");
		keyWordsOriginais.put(8,"nacional,nacionais,internacionais,mundo,assassinato,policia,sequestro,relampago,morte,overdose,drogas,chacina,crime,venda,compra,alugase,locacao,troca,descoberta,pesquisa,cientistas,pesquisadores,conhecimento,espaco,sideral,entretenimento,economia,ciencia,esportes,clima,tecnologia,turismo,politica,brasil,geral,noticia,cafecomnoticia,novidade,toda_regiao,portal,fato,");
		keyWordsOriginais.put(9,"religiao,religioso,sagrado,biblia,deus,jesus,evangelho,novo_testamento,antigo_testamento,catolico,evangelico,espirita,fe,igreja,templo,cristianismo,budismo,judaismo,islamismo,hinduismo,espiritismo,religiosa,batismo,catequese,comunhao,mitologia,deuses,exorcismo,macumba,candomble,eva,adao,adoracao,alan_kardec,alcorao,amem,ateismo,basilica,batizado,bencao,bhaga,buda,cabala,calice,capelao,cardeal,catedral,catequista,celibato,corao,corpus,crisma,cultos,dalai,lama,dharma,dogma,doutrina,encarnacao,estado,nirvana,eucaristia,evangelio,ewa,farao,freiras,ganesha,ganga,graca,hanuman,homilia,indra,kabbalah,kama,karma,laxmi,logun,ede,maome,medium,misticismo,moammed,monge,muculmanos,nna,buruku,obaluaye,ogun,gun,olorum,oracao,orixa,ortodoxo,osanyin,osossi,sumre,pagao,passe,pecado,peregrinacao,profecia,quaresma,redencao,ressureicao,reza,rito,ritual,sacerdocio,sacerdote,sacramento,samsara,sangha,sngo,sarasvati,seita,shiva,smrti,sruti,surya,teologia,terrero,tora,uncao,veda,vigilia,pascal,vixnu,vodu,xama,xamanismo,yama,missa,nossa_senhora,evangelica,milagre,caminhodedeu,deu,missoe,maconaria,macon,unidademaconica,chico_xavier,liturgia,santo,papa,");
		keyWordsOriginais.put(10,"bodas,diamante,autoajuda,relacionamentos,doencas,alergias,remedios,farmacias,renite,vestido_noiva,buffet,aliancas,investimentos,creche,colonia_ferias,maternal,gravidez,gestante,cuidados_bebe,cuidado_crianca,educacao_filhos,cuidado_filhos,");
		keyWordsOriginais.put(11,"alimentacao,comida,comidas,bebidas,bebida,frutas,verduras,saladas,massas,ovos,leite,laticineos,hotalicas,cereais,paes,carnes,carne,vermelha,branca,frutos,mar,vitaminas,vinho,tinto,suave,seco,cerveja,importada,vodka,tequila,whisky,uisque,jack,daniels,johnnie,walker,artesanal,heineken,budwaiser,corona,duff,jose,cuervo,bhrama,bares,restaurante,guia,restaurantes,quilo,fast,food,delivery,entrega,pizza,pizzarias,chinesa,lanchonetes,lanches,sanduiche,burguer,hamburguer,fastfood,mcdonalds,receitas,vegetarianos,vegetariano,vegan,culinarias,culinaria,dicas,curso,doceira,receita,bolo,frango,gastronomia,goumert,charutos,tabaco,pratos,sofisticados,cozinha,francesa,italiana,");
		keyWordsOriginais.put(12,"cvc,turistico,viagem,viagem_nacional,viagem_internacional,turismo_ecologico,viagens,pousada,fazenda,albergue,camping,resort,reveillon,destino,mochilao,mochileiro,cruzeiro,visto,passaporte,consulado,veraneio,casa_de_praia,passagem,aeroporto,rodoviaria,primeira_classe,segunda_classe,onibu_leito,onibu_executivo,confin,airway,southwest,viaje_por,viaja_por,intermunicipal,John_F_Kennedy,La_Guardia,American_Airlines,Southwest_Airlines,Pluna,Aeromexico,Air_Canada,Air_France,Aerosur,Copa_Airlines,Lufthansa,British_Airlines,US_Airways,Aeroporto_Internacional,Passagem_Internacional,Afonso_Pena,Augusto_Severo,Campo_dos_Palmares,Catarata,Confins,Congonhas,Cumbica,Cruzeiro_do_Sul,Dep_Luis_Eduardo_Magalhaes,Eduardo_Gomes,Tom_Jobim,Guararapes,Hercilio_Luz,Juscelino_Kubitschek,Marechal_Rondon,Pampulha,Pinto_Martins,Presidente_Castro_Pinto,Presidente_Medici,Regional_do_Cariri,Salgado_Filho,Santa_Genoveva,Santa_Maria,Santos_Dumont,VaideCans,Viracopos,Guarulhos,passagem_aerea,voo_internacional,executivo,pedagio,voo,webjet,aerea,translado,delta,checkin,milhagem,milhas,");
		keyWordsOriginais.put(13,"game,world,video_game,jogo,player,computador,rede,wii,playstation,psp,nintendo,xbox,kinect,console,warcraft,diablo,counter,strike,cassino,poker,roleta,tabuleiro,cartas,baralho,xadrez,damas,domino,varetas,sinuca,tenis,mesa,pingpong,pebolim,banco,imobiliario,perfil,twister,peao,corda,confronto_final,jogue,manha_de_jogos,manha_games,jogos,war,canastra,truco,robamonte,pife,naval,dorminhoco,trunfo,drinking,ludo,gamao,uno,sueco,monopoly,master,junior,palavras,cruzadas,memoria,cacheta,tranca,");
		keyWordsOriginais.put(14,"arte,cultura,movimento,cultural,arte_visuai,arte_visual,contemporanea,classica,medieval,moderna,antiga,popular,historia,museu,museus,exposicoes,galeria,pintura_famosa,monalisa,pintore_famoso,louvre,mona_lisa,obra,velazques,giorgine,tatuagem,feminina,masculina,tatoo,tribal,dragao,oriental,tatuagens,desenhos,tatuar,tatuador,artesanato,trabalhos,manuais,bordado,croche,trico,biscuit,pintura,ceramica,decoupage,escultura,patchwork,scrapbook,bibliotecas,livrarias,ebooks,feira,livro,clube,sebo_online,teatro,pecas,peca,teatral,atores,cartaz,municipal,guaira,programacao,circo,cirque,soleil,danca,festival,tutoriais,apresentacoes,opera,salao,folclore,folclorica,folclorico,");
		keyWordsOriginais.put(15,"entretenimento,diversao,variedade,passatempo,distracao,recreacao,animacao,desenho,animado,disney,infanti,classico,pixar,crianca,quadrinho,historia_em_quadrinho,revista,manga,bidu,franjinha,download,critica,cartaz,cinema,programacao,festival,oscar,premiacoe,personagen,atore,atrize,humor,meme,tirinha,piada,parodia,pegadinha,comedia,zoacoe,horoscopo,chine,tarot,esoterismo,leitura,astrologia,numerologia,mapa,astral,simpatias,anjos,colecionismo,objeto,colecionavei,miniatura,selo,moeda,antigas,figurinhas,signo,raridade,colecao,cartoe,telefonico,hobbymodelista,programa_de_televisao,televisao,rede,globo,novela,auditorio,record,band,cultura,reality,show,celebridade,gente,famosa,famosos,ator,atriz,exbbb,fofocas,flagras,colunas,sociais,paparazzi,paparazzo,musica,orquestra,sinfonia,bandas,cantores,cantora,cantor,letras,traducao,eletronica,danceteria,casa_noturna,eventos,noturnos,noite,livre,pesca,camping,piquenique,passeio,parque,balonismo,brincadeira,banho,chuva,rigtone,wallpaper,emoticon,mensagen,prontas,gifs,emotions,aniversario,formatura,dica_para,certo_para_seu,incrivel,bizarro,trasnformacao,fantasia,inacreditavel,misterioso,suposta,filme,game,cultura_pop,imagem_engracada,para_facebook,sem_sentido,curiosidade,tv,serie,telhacast,designando,bacana,podcast,matracacultural,");
		keyWordsOriginais.put(17,"cursos,presenciais,distancia,qualificacao,profissional,educacao,educacional,livros,carreira,aprendiz,emprego,vagas,curriculo,entrevista,primeiro,vitae,experiencia,admissao,didaticos,material,didatico,dicionario,calculadora,enciclopedias,autodidata,conteudo,multimidia,aprendizado,educativo,vestibular,feira,profissoes,teste,vocacional,curso,dicas,enem,mundovestibular,guia,estudante,medicina,exercicios,tecnico,nivel,medio,informatica,profissionalizante,senac,cenpro,graduacao,faculdade,universidade,tecnologos,superior,estagio,ciee,federal,publica,particular,puc,especializacao,mba,posgraduacao,extensao,fgv,master,business,administration,mestrado,doutorado,scricto,capes,anpad,dissertacao,exatas,biologicas,humanas,concursos,publicos,editais,abertura,concurso,gabarito,federais,municipais,estaduais,concorrencia,");
		keyWordsOriginais.put(18,"comercio,industria,empregado,chefe,patrao,gerente,diretor,socio,acionista,investidor,internacional,exterior,importacao,exportacao,camara,americana,amcham,plano,negocios,consultoria,treinamento,empresas,artigos,micro,pequena,empresa,empresario,escritorio,administracao,administrador,executivo,empreendedorismo,agronegocios,pecuaria,agricultura,animais,vaca,touro,plantacao,equitares,chacara,recursos,humanos,rh,recrutamento,selecao,pessoas,competencias,avaliacao,indicador,desenvolvimento,humano,conarh,gestao,marketing,agencia,publicitaria,publicidade,propaganda,midia,meios,comunicacao,reporter,jornalismo,eventos,relacoes,publicas,virtual,webmarketing,email,redes,sociais,midias,digitais,seo,design,webdesign,edicao,imagens,photoshop,corel,draw,fontes,grafico,moda,motion,bolsa,valores,cambio,economia,pib,nova,york,dolar,euro,real,nacional,alta,queda,crise,financeira,pregao,cfm,conselho,federal,medicina,crm,profissional,saude,softwares,medicos,equipamentos,cursos,area,residencia,medica,material,cirurgico,esterilizacao,maca,ecologia,sustentabilidade,reciclagem,meio,ambiente,ecologista,ernst,haeckel,eugenius,warming,poluicao,ecologicamente,correto,economicamente,viavel,socialmente,justo,culturalmente,diverso,energia,nuclear,industrias,fabrica,montadora,maquinario,controle,qualidade,leis,advogados,advogado,promotor,juiz,processo,juridico,danos,morais,psicologicos,indenizacao,professor,pedagogo,educador,escola,escolar,funcionarios,administrativos,escolas,funcionario,administrativo,faculdade,agente,viagens,hotelaria,turismo,hoteis,");
		keyWordsOriginais.put(19,"tecnologia,inovacao,tecnologica,novidades,digital,corporativa,download,foruns,curiosidades,tech,notebook,laptops,netbooks,pavillon,lenovo,monitores,pc,monitor,lcd,desktops,chips,cpu,acessorios,pen_drive,projetor,multimidia,placa_de_video,impressora,cartucho,toner,impressoras,deskjet,laserjet,roteador,conector,rede,firewall,hub,modem,switch,software,utilitarios,linux,window,desenvolvimento,desenvolvedor,programador,linguagem,programacao,banco,dados,desenvolvedores,programadores,pro,app,store,artes,digitais,fotografia,cameras,fotograficas,filmadora,filmagem,telefonia,aparelho,telefone,tablet,capa,celular,smartphone,operadora,sinal,pendrive,atalho,senha_padrao,usuario,bluetooth,aplicativo,cabo,hacker,hackeia,geek,backup,reparo_computador,maniadeeletronico,tecnopot,google,plus,fonte_de_tecnologia,");
		keyWordsOriginais.put(63,"venda,compra,aluga_se,locacao,troca,usado,seminovo,diretorio,Lista_de_lugar,anuncie_gratis,lista_da_cidade,guia_da_cidade,listadacidade,troca_de_usados,cupom_de_desconto,desconto,compras_online,vendas_online,promocao_online,venda_online,cupom_de,barato,baratovip,compra_no_exterior,onde_comprar,fedex,compra_online,produto,loja_online,shopping_virtual,guia_do_bairro,encontre_produto,loja_da_regiao,santaefigeniaonline,divulgacao,melhor_em_venda,seu_canal_de_vendas,comercio_da_regiao,loja,classificado,tonaduvida,");
		keyWordsOriginais.put(103,"Ongs,Trabalho_voluntario,Caridade,Filantropia,Ajuda_humanitaria,Ativismo_Ambiental,WWF,Green_Peace,Instituto_Akatu,Cenpec,Instituto_Ethos,Instituto_de_Reciclagem_do_Adolescente,Associacao_Educacional_Labor,Missao_Crianca,CIPPEC,Fundacion_Cimientos,Fundacion_Compromiso,Fundacion_Conciencia,Fundacion_Proyecto_Padres,SES,A_Roof_for_my_Country,Cenfa,Protecao_Ambiental,Protecao_aos_Animais,Instituto_Maria_Preta,Casa_do_Artista,Pastoral_da_Crianca,Embaixador_da_ONU,Embaixatriz_da_ONU,");
		keyWordsOriginais.put(189,"justin,bieber,beijo,revistas,teen,selena,gomez,amor,paquera,idolos,demi,lovato,papo,bff,taylor,swift,blogcapricho,manugavassi,topteen,caio_castro,");
		keyWordsOriginais.put(190,"playboy,ensaio_sensual,foto_nua,caiu_na_rede,mulhere_linda,porno,gata_nua,gata,Making_of,jovem_nua,sem_tarja,caiu_na_net,video_de_sexo,capa_playboy,foto_playboy,sexy,nua,nua_na_webcam,posou,posou_nua,revista_Vip,revista_masculina,gata_sensual,musa_da_semana,sexxxy,musa_do_time,musa_do_sao_paulo,musa_do_flamengo,musa_do_palmeira,musa_do_atletico,musa_do_corinthian,musa_do_vasco,musasfc,musa_do_futebol,sem_calcinha,de_biquini,nua_em,nua_em_cena,video_intimo,gostosa,pelada,puta,video_privado,broma,caliente,");
	}

	static {
		keyWordsReduzidas = new HashMap<Integer, String>();

		keyWordsReduzidas.put(1," lapis plastica lantejoulas mechas silicone tendencia colete batons unissex blush cinto masculino cirurgia estrias infantil longo celulite creme visual feminino penteados olho base bebe hair tratamentos rosto unhas cores perfumes vestido roupas esmaltes cabelos cabelo beleza maquiagem moda ");  
		keyWordsReduzidas.put(19," toner projetor artes cartucho filmadora filmagem cameras deskjet switch multimidia window programadores atalho placa_de_video linguagem acessorios lcd usuario roteador programador monitor conector capa pendrive telefonia desenvolvedor cabo pen_drive hub firewall cpu novidades sinal desenvolvedores chips laptops corporativa store modem hacker curiosidades plus bluetooth impressoras banco netbooks telefone notebook monitores geek backup desktops tech lenovo operadora pro fotografia digital tecnologia tablet digitais smartphone software app aparelho celular pc download dados aplicativo impressora rede desenvolvimento linux google ");
		keyWordsReduzidas.put(18," comunicacao hoteis avaliacao residencia draw publicitaria ecologia industria morais socialmente webmarketing viavel diverso midias industrias amcham cambio agencia medicina administrativos economicamente justo competencias animais micro nuclear jornalismo area funcionario imagens hotelaria escolar juiz administracao promotor turismo agente moda ernst danos dolar fabrica seo funcionarios humano reciclagem meios softwares leis indicador advogados correto euro vaca comercio crm advogado york escolas viagens empregado negocios investidor pib acionista montadora chefe material real treinamento escola recrutamento pequena propaganda ambiente professor meio agricultura administrativo nova design faculdade equipamentos sociais internacional rh redes fontes consultoria email financeira pessoas virtual controle exterior profissional eventos americana queda federal energia artigos conselho sustentabilidade humanos nacional desenvolvimento diretor digitais processo recursos qualidade gerente administrador executivo empreendedorismo alta plano cursos marketing publicidade empresa bolsa crise valores economia empresas ");
		keyWordsReduzidas.put(7," alugar apartamento sala corretor casa sobrado planta ");
		keyWordsReduzidas.put(8," overdose politica novidade nacionais descoberta compra turismo ciencia internacionais venda policia noticia cientistas tecnologia pesquisadores troca assassinato entretenimento clima drogas esportes conhecimento portal brasil geral mundo crime morte fato pesquisa economia nacional ");
		keyWordsReduzidas.put(9," islamismo religiao freiras corpus corao cabala calice oracao pagao alan_kardec comunhao logun eva samsara ortodoxo adoracao misticismo catolico evangelico karma celibato veda dalai dharma ateismo graca budismo macumba espirita quaresma sacerdocio homilia pascal sacramento dogma catequese mitologia monge evangelica reza lama crisma passe batizado liturgia amem eucaristia cardeal sagrado estado ritual cultos espiritismo chico_xavier missa exorcismo nossa_senhora religioso batismo fe deuses catedral religiosa seita profecia papa sacerdote milagre deu cristianismo teologia evangelio templo evangelho pecado santo rito catequista jesus novo_testamento antigo_testamento doutrina deus biblia igreja ");
		keyWordsReduzidas.put(63," venda compra usado loja produto barato ");
		keyWordsReduzidas.put(12," viaja_por segunda_classe executivo pedagio Pinto_Martins Pampulha Pluna intermunicipal primeira_classe Santa_Maria voo_internacional Air_Canada checkin passagem_aerea Air_France Salgado_Filho Lufthansa American_Airlines Aerosur Santos_Dumont US_Airways viagem_internacional aerea turistico Confins milhagem translado delta Aeroporto_Internacional consulado cvc rodoviaria fazenda reveillon mochilao Congonhas resort Guarulhos milhas passaporte cruzeiro pousada mochileiro albergue voo visto destino aeroporto passagem viagens camping viagem ");
		keyWordsReduzidas.put(14," artesanato louvre livrarias desenhos folclore pintura cartaz bibliotecas escultura circo movimento museus moderna municipal historia museu atores livro trabalhos antiga obra teatral festival arte galeria popular teatro cultural clube feira cultura ");
		keyWordsReduzidas.put(15," numerologia aniversario inacreditavel selo casa_noturna parodia exbbb noturnos auditorio variedade dica_para suposta bacana orquestra prontas formatura bidu mapa leitura signo astral manga sinfonia celebridade pixar objeto cantores parque paparazzo fantasia eletronica bandas critica chuva tirinha brincadeira disney paparazzi colunas comedia cultura pegadinha serie fofocas quadrinho antigas desenho record podcast banho livre curiosidade band sociais flagras animado gifs cultura_pop piada oscar meme cantor cantora famosa ator misterioso rede passeio anjos musica atriz eventos festival game cartaz download reality noite letras incrivel gente show novela globo revista filme famosos entretenimento bizarro tv humor cinema ");
	}
	
	static {
		keyWordsCandidatasOriginais = new HashMap<Integer, String>();

		keyWordsCandidatasOriginais.put(1,"cabelo maquiagem pele fashion moda nutricao inverno cabelos usar jeans spfw lia look tendencias desfiles vistas beleza rosto mariah tratamento corpo verao tendencia proibida colecao looks carolina just responde oculos pilates outono meninas trend tratamentos algodao resistencia juliana vestidos esmaltes saia english ginastica estampa estilo saudavel esmalte fa ioga aleatoria oleo contacte jejum portuguese aptidao mentacao dietas style plus rios autores comportamento chic lingerie campanhas amei jessica vestido ltda cor perfumes acessorios prada entrantes limpeza kate lala acompanhe paes maquiagens gucci pesquisar sapatos mistura calca femininos modices acne corte valentino perfumaria relacionamento elementos dolce blazer hair inspiracao dieta presentes gabriela");
		keyWordsCandidatasOriginais.put(19,"windows galaxy android tela amazon ipad gadgets multimidia tablets microsoft motorola apple linux baixados fi reviews wi info cientistas confirma asus vagas utilizadas iphone botao ios protestos parecida descobrem teletransporte inadequado games apps ultra iniciar rights reserved adia samsung glass atingem chuvas marte crescem sonda roteadores comemora aplicativos active proibe aplicativo vazam compara bloqueio shopping mencoes tiveram turquia robos recorde propoe exagero institucional comentadas aparelho pirata assassinos toneladas onu mobility nokia apresenta redes downloads indiano cardiacas skype cirurgias mobile assinaturas moto tutoriais youtube fortes mini avg etica forum rus antiva zigg lanca bizarro impressora lg desenvolvimento all hd google especialista");
		keyWordsCandidatasOriginais.put(18,"carreiras mercados papeis investidores mineracao servira agronegocio ibovespa chamam moedas mina conversor termometro doha omc retomada financas desprezados bali brando economica infraestrutura reuniao indique reuters enhanced thomson var deseja economicos avancar w ig indicadores economico portais papo ibest z texto crise moeda empresas virtuais cambio brturbo industria banner pessoais valores trainee mundial ouro crimes acelerador original colunas j comercio bolsa estagio delas conheca bate sites cliente propria t u tera resultado antivirus digite usados valor conteudo assine k vendas venda ultimo termo futebol negocio buscar renda v h relacionadas atencao indice bolso data investimentos compra c termos l semestre esportes");
		keyWordsCandidatasOriginais.put(7,"imobiliaria planta condominio terrenos sobrado conceitos portas sofa almofadas basicos fazendas terreo hidraulica truques churrasco tapete socorros cadeira externa tijolo laje bloco domesticos redondo beliches sapateira barbante paisagismo imoveis tulipa parapodium nessessita consiguindo belihe utensilios reforma caseiro infantis maravilhoso piso apartamentos pascoa sitemap construcao patrocinadores formato imovel mix piclens moveis kit adorei artesanato decoracao culinaria imobiliario cama ideal corretores corretor flores primeiros apartamento projetos maio pagamento fevereiro dezembro escolher encontra outubro posso novembro agosto setembro julho recentes rosa tipos rurais queria view formas junho casas categorias cancelar abril creci turismo populares lazer anuncios feliz autos arquivos obrigatorio corretora famosos urbanos");
		keyWordsCandidatasOriginais.put(8,"colunistas educacao cpi acervo reinaldo lauro furquim setti julgamento mensalao augusto impostos nunes neiva azevedo cachoeira erros coluna ciencia line caio internacional fernanda eleicoes radar jardim share seguro blinder paula sergio cotacoes renato temas maquiavel top celebridades conversa peso aula dutra ministro edicoes isabela listas ricardo cronologia beber reportagens conhecimentos boscov enem galeria villalba genetica noticiario tony enquetes olimpiadas esporte dermatologia pimenta mandel zatz mayana infograficos imperdivel escritores rodrigo noticia bellotto fisica ribeiro economia saude profundidade york sac lucia aponte vendidos operacao drama contas antonio variedades patricia rodrigues lula acompanha siria sp abertas bombeiros incendio mortes iba palavroes ofensas escandalo");
		keyWordsCandidatasOriginais.put(9,"biblia igreja atos samuel doutrina genesis heresias apologetica jerusalem catolica espiritualidade testamento biblico tito joel sagrada seitas protestantismo ester jonas salmos amos king cnbb biblias lucas traducoes public pueblo timoteo dicionario leituras biblica nt american bible proverbios ave neo septuaginta vulgata des dios sainte standard rheims raamattu transliterada domain ezequiel sacra catholic bibel katolikus community augustin clecia revised hrvatski douay jerusalen libro chretiennes tysi die bibbia latinoamericana crampon communautes biblija daniel romanos deuteronomio judas josue jesus isaias baruc galatas exodo esdras efesios eclesiastes habacuc eclesiastico deus filipenses levitico filemon pentateuco evangelhos new profeticos sapienciais christian sinoticos marcos epistolas santos james");
		keyWordsCandidatasOriginais.put(63,"bcash buscape bondfaro causas quebarato discriminatorios terroristas difamatorios invasivos bit obscenos abusivos danosos menores informatica cortacontas publicar conectado ofertas frete vendedor relacionamentos entregar informadas responsabilidades angola motos compradores panama guatemala bissau macau honduras nicaragua timor gratis saveme cabo rica dominicana tome terceiros ilegais preservacao agressivos ameacadores caluniosos condenaveis prejudiciais portugal anuncio confiometro lcd lomadee colombia venezuela console editar principe filtrar rico peru anunciar virtual adicione ordenado productos pago oferta popularidade full chile vulgares anunciantes vender ingresar politicas tienda producto company ayuda argentina cualquier terminos materiales sean conoce agresivos ilegales terceros naturaleza condenables amenazadores preservacion calumniosos costa comprar recomendado contrario todavia");
		keyWordsCandidatasOriginais.put(12,"viajar destinos camping trilhas viagem roteiros registre albergues relatos avancada ativos travessias lida aventura viajante registrado impressao localizacao equipamentos exibir faq re alterar companhia paises horarios jan navegando resumo registrar excluir painel ordenar gmt sitemapindex list viagens channel topicos passeios fev mochileiros tamanho onibus roteiro hoteis crescente indice decrescente cookies pegar nov relato phpbb traduzido passagem jul mensagem responder km abracos visitantes sul semanas valeu fui colaborador set umas out galera seo mar restaurantes passagens anteriores trem lugares uns aeroporto ago hotel ir conhecer abr topo fiz fonte mensagens website ida forum regras visitar voltar indo parque entrar praias jun");
		keyWordsCandidatasOriginais.put(14,"cultmerc cemec enviado realizacao colaboradores toma editorial vive altas investigacao realizado mandato cavalo artistas comemoracao arma cumprimento clube assessor aparecida encontrada socorro apreensao enfrentamos realizando ralo expedido resende rocas recebemos aguardem cocais taquaracu hibisco ione alesson assa jui barao pemaq emboabas uaitec caete vcnanet furtados catas follow industrial foco fatos entender geraldo dsc recurso distrito slideshow aniversario barbara javascript esqueceu mudancas avenida horoscopo desfile agenda popular camara dificuldade grana certa vip uniao visao solta falando conosco goncalves lembrar novelas fale civil breve equipe culturais teatro pede pedra quarta cultura aconteceu sonhos cultural quinta branca social minas medo bairro entretenimento pinheiro");
		keyWordsCandidatasOriginais.put(15,"tirinhas automoveis premios rock exibe cenas cinema menina nerd bbb bebe comenta house dispara visitas jogadores namorado animes ensaio namorados novela teen link adulto mulher curiosidades estranha box cliques sertanejo carnaval automatico banners sumario amor frequentes william loira buscas agregador logs enviou tatuagem celebridades motocicletas rn estatisticas gambiarras dohits criancas garota atores sexy ndchen gigante musica cadastro gatas episodio provar provas exibido resumos lanches porno atitude bruno famosas entrevistas mamae juliano pizza gostosa malhacao transparente legendado joe corpao promocoes gostosas tocontigo bombando dublado netinho confirme risadas sampaio acertar ellen clickgratis blogs cola cacula vinganca filme religiao facebook tv isis declara");
	}
	
	static {
		keyWordsCandidatasSteme = new HashMap<Integer, String>();
		
		keyWordsCandidatasSteme.put(1,"cabel maqui moda fashion tendenc invern nutrica beleza estamp corpo esmalt look spfw vest je mariah noiv mak mod diet vistas ole lingeri coleca masc lia vera trend marca pilat rost cabelo sauda resistenc english ginas busca estil aleator ocul aptida mentaca jejum iog algoda contacte plu perfum acesso corp calc crem pele styl cint pente bel reproduca ltda proced separ pae camiset tabel lala fin exercici calor modic gucc maquiagem ame dolc lookbook gabb nin ferraz blaz desfil acn siz hall cor comport inspiraca carolin unh banan middleton carpet chanel fend galoch brilh flor cosme klein pol manch antigo");
		keyWordsCandidatasSteme.put(19,"window galaxy android ipad gadget amazon multimid microsoft motorol appl review linux info wi topic tel inf asu assinat bota vag iphon io teletransport inadequ cient ultr app right reserved samsung adi mobil glas sond aparelh comem robo pirat menco turqu bloquei instituc propo tonel exagero tablet cardiac onu bizarro mobility nok shopping indi googl skyp hd download vaz youtub gam etic avg forum confirm ru antiva zigg tutor lg impres bullet titulo tchec mart all aplic discutira ciberespion smartphon rote glob protest disposi hospit phon ating hardw map reservados operaca cirurg revist nas edition desenvolv instal party resoluca campu");
		keyWordsCandidatasSteme.put(18,"economia papeil economico infraestrut reunia mineraca servira agronegoci ibovesp retom conver desprez doh termometr omc reut indiqu enhanced thomson w ig portais ibest z cris sobre moed cambi brturb bal fonte financ aceler traine our text crim comerci estagi empr j client pap industr bann agor hoj momento conteud invest pessoal texto antiviru atenca propr k desej u result bols futebol carr orig administraca merc tera h vend assin dat empresas virtual t empresa avanc semestr q aposentad econom group esport wikinom c colun br eik y convenc m var trabalh gent b indic bat v conhec logis ult cham");
		keyWordsCandidatasSteme.put(7,"imobiliar imoveis terren condomini terre construcao moveis decoracao sofa almof reforma apartamentos truqu churrasc hidraul tapet casas imobiliaria condominio tijol bloc laj paisag externa belich portas tulip parapodium belihe nessessit consigu utensili domesticos fazendas paisagismo terrenos imovel apart rosa projetos pasco construca domes extern conceit reform plant pis mix piclens laz imobilia todas sitemap movel artesanat decoraca infantil patrocin fazend culinar sapat socorr cade fever dezembr dicas outubr kit maravilh novembr julh format noticias setembr bom agost ideal junh rural aut planta obrigato tur arqu corretor abril alugar creci basic fl crec categor feliz redimob laud perit updat salario newsletter");
		keyWordsCandidatasSteme.put(8,"educaca cpi acerv veja reinald furquim sett mensala august neiv azeved nun julg cacho impost lin laur cienc eleico rad fernand sh aul sergi colun cotaco internac isabel publicado jardim vestibul cai imperdivel edico drama cronolog ricard boscov nunes escri noticia celebr palavras ribeiro rodrigues olimpi rede setti tony reportagens gene azevedo dermatolog mandel blinder estudo mayan zatz infograf ministr dutra renat neiva villalba pimenta esport bellotto maquiavel saud enquetes rodrig testes antoni imagens york operaca econom profund segur provoc pes patric escandal fisic videos sp lul temp incendi iba gal candidat govern parlament palavroes externos lingu opinioes vulg ofensas");
		keyWordsCandidatasSteme.put(9,"bibl igrej samuel doutrin espiritual heres genesil catol ato jerusalem seit sagrad amo evangelh joel ose salm protestant apologe jud king cnbb galat sacr traduco rut profe puebl proverbi diciona tit nt american timote ave neo vulgat dio biblias deuteronomi septuagint catholic standard raamattu augustin domain rheim ezequiel chretienn douay bibel communaute clec jerusalen community revised transliterada tysi bibb die biblij hrvatsk latinoameric katoliku crampon esdr josue exod isai baruc judit filemon efesi habacuc filipens levi mique pentateuc apostol sino sapienc epistol christian latin jesu iii daniel jo reil saint jam version libr eclesias apocalips luc leit roman cron joa");
		keyWordsCandidatasSteme.put(63,"bcash buscape bondfar quebarato discriminatorios terroristas difamatorios invas danosos obscen abusivos prejudic men bit cortacont conectado anuncio modo gratil fret informadas angol hond guatemal bissau panama macau nicaragu motos informatica lazer usado lomade savem venezuel condicion dominic vulgares portug tome colomb terceiros ilegais agressivos preservaca ameacadores caluniosos condena confiometr consid lcd loja ofert peru preco argentin chil product popular full respons tiend ingres company cualqui productos conoc ayud encuentr sean agresivos ilegales apoy condenabl amenazadores preservacion terceros pregunt calumniosos favor parcel categori filtr todavi contra inmuebl vehicul configuracion emple publicacion descripcion mensaj frete espa paraguay busqued ecu verif autos asum");
		keyWordsCandidatasSteme.put(12,"registre camping alberg viag trilh travess rot viaj avent relat impressa mensagens localizacao faq companh alter destin re viagem horari exclu painel gmt sitemapindex channel fev passei anteriores tamanh decresc agora mochileiros cooki font exib pais traduz phpbb km resum hosped lug mochil sul out hotel onibu onibus ativ seo avanc regr voo ilh ago parqu hoteil restaurant registr mochila aeroport websit forum ind ida map visit prim turist naveg jul respond cidade indic europa vou aere pena nenhum hostel prai fiq escreveu gui equip turis mens feed atraco cidad tr titul html orden powered saind abrac carro fui galera");
		keyWordsCandidatasSteme.put(14,"cultmerc cemec realizaca registrar entretenimento caval mandat assessor recurso comemoraca entre fatos lembrar mudancas branca roc furt pinheiro investigacao apreensa ion exped ral taquaracu hibisc alesson assa aguardem cocal emboabas jui resend caete pemaq vcnanet uaitec bara follow imagem cultura gerald dsc dificuldad cat slideshow distrit horoscop javascript aven foc fez enfrent club agend conosc blogs unia artistas goncalv visa artist cumpr civil gran aniversa quinta solt cult senha nest usuario bairr colabor teatr artis culturais vip desfil poder semana entend cultural realiz arm novel lix acontec alv atrave domingo arte relaca tags fal art hom denunc foi presid ultimas");
		keyWordsCandidatasSteme.put(15,"anim nerd premi gat cinem rock bebe bbb cen estranh brun log bizarr cadastro adult house links bell teen conteudo agreg cachorr carnav box music utilidad dent frequ mama sertanej loir sumari motociclet ris gigant automatico acert rn dohit bale curios religia menina ndchen crianc sexy celebr geme namorado ensai fur flagr world promoco gostou bod dubl porno contigo trail episodi mamae greg novel edica corpa maluc joe barriga porr nega novela gamb tocontig ellen clickgratil hum exibido transpar sampai tiv mulh coment facebook isil decl bad fei confirme cacul vinganc two tri felix mulher tv mr valv isabell vampir");
	}
	
	public static String[] getkeyWords(int keyWordType, int categoriaEsperada) {
	
		PTStemmerEX stemmer = new PTStemmerEX();
		//String [] keywords;
		
		if (keyWordType == originais){
			String [] keywords =  keyWordsOriginais.get(categoriaEsperada).split(",");
			return keywords;
		} 
		else if (keyWordType == originaisSteme){
			String [] keywords =  keyWordsOriginais.get(categoriaEsperada).split(",");
			for (int i = 0; i < keywords.length; i++) {
				keywords[i]= stemmer.execStemming(keywords[i], orengoStemmer);
			}
			return keywords;
		} 
		//pega as keywords com o OU entre elas
		else if (keyWordType == originaisOU){
			String [] keywords =  new String[1];
			keywords[0] = keyWordsOriginais.get(categoriaEsperada).replaceAll(",", " ");
			return keywords;
		}
		else if (keyWordType == originaisOUSteme){
			String [] keywords =  new String[1];
			keywords[0] = stemmer.execStemming(keyWordsOriginais.get(categoriaEsperada).replaceAll(",", " "), orengoStemmer);
			return keywords;
		}
		//pega as keywords reduzidas
		else if (keyWordType == reduzidasOriginais){
			String [] keywords =  new String[1];
			keywords[0] = keyWordsReduzidas.get(categoriaEsperada);
			return keywords;
		}
		else if (keyWordType == reduzidasSteme){
			String [] keywords =  new String[1];
			keywords[0] = stemmer.execStemming(keyWordsReduzidas.get(categoriaEsperada), orengoStemmer);
			return keywords;
		}
		//pega as keywords candidatas
		else if (keyWordType == candidatasOriginais){
			String [] keywords = keyWordsCandidatasOriginais.get(categoriaEsperada).split(" ");
			return keywords;
		}
		else if (keyWordType == candidatasSteme){
			String [] keywords = keyWordsCandidatasSteme.get(categoriaEsperada).split(" ");
			return keywords;
		}
		
		return null;
	}
	
}
